---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-git

inputs:
  - name: git-repo
  - name: version

run:
  path: git-repo/ci/tasks/restart.sh

params:
  GIT_REPO:
  PASSWORD:
  S3_BUCKET:
  S3_ACCESS_KEY_ID:
  S3_SECRET_ACCESS_KEY:
  S3_BLUE_GREEN_FILE:
