---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-git
    tag: "latest"

inputs:
  - name: git-repo
  - name: blue-green

outputs:
  - name: git-repo-output
  - name: blue-green-output

run:
  path: git-repo/ci/tasks/restart.sh

params:
  # GIT_REPO:
  # SSH_KEY:
